version: "3.3"

services:
    
    standard_node1:
        image: bayrell/cloud_os_standard:0.4.0
        hostname: "cloud_os_standard_node1_1.local"
        volumes:
            - "standard_node1_data:/data"
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
        ports:
            - "8080:80"
        env_file:
            - ./env.conf
        environment:
            TZ: "Asia/Almaty"
            WWW_UID: 1000
            WWW_GID: 1000
        restart: always
        networks:
            - cloud_network
        logging:
            driver: journald
    
volumes:
    standard_node1_data:
    
networks:
    cloud_network:
        external: true
